### ISSUE TITLE
Mode 0 error  KeyError: "[('timestamp', 'src_ip', 'dst_ip')] not found in axis"

### ISSUE THREAD

**Issue by monarchinc** [AbertayMachineLearningGroup/MQTT_ML#2]
command : `%run classification.py --mode 0 --output packet --verbose True`

I am having trouble to generate output for packet (mode 0) Mode 1 and Mode 2 are working fine 
Detailed error message is described below used both original and updated codes in the initial Issue.

output message: Starting Slice #: 0
Start Classification
C:\Users\user\Desktop\MQTT_ML\classification.py:75: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv(path)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~\Desktop\MQTT_ML\classification.py:275, in <module>
    272 if os.path.isdir(folder_name) == False:
    273     os.mkdir(folder_name)
--> 275 x, y = load_file(prefix + 'normal.csv', 
    276                  args.mode, 
    277                  0, 0, 
    278                  folder_name, 
    279                  slice_number,
    280                  args.verbose)
    282 x_temp, y_temp = load_file(prefix + 'scan_A.csv', 
    283                            args.mode, 
    284                            1, 1, 
    285                            folder_name,
    286                            slice_number,
    287                            args.verbose)
    289 x = np.concatenate((x, x_temp), axis = 0)

File ~\Desktop\MQTT_ML\classification.py:85, in load_file(path, mode, is_attack, label, folder_name, sliceno, verbose)
     79 #            if is_attack == 0:
     80 #                dataset = dataset.loc[operator.and_(dataset['ip_src'].isin(attacker_ips) == False, dataset['ip_dst'].isin(attacker_ips) == False)]
     81 #            else:
     82 #                dataset = dataset.loc[operator.or_(dataset['ip_src'].isin(attacker_ips), dataset['ip_dst'].isin(attacker_ips))]
     83 #            
     84         if mode == 0:
---> 85             dataset.drop(columns=[columns_to_drop_packet], inplace = True)
     86             dataset = dataset[dataset.columns.drop(list(dataset.filter(regex='mqtt')))]
     87         elif mode == 1:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py:311, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    305 if len(args) > num_allow_args:
    306     warnings.warn(
    307         msg.format(arguments=arguments),
    308         FutureWarning,
    309         stacklevel=stacklevel,
    310     )
--> 311 return func(*args, **kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py:4948, in DataFrame.drop(self, labels, axis, index, columns, level, inplace, errors)
   4800 @deprecate_nonkeyword_arguments(version=None, allowed_args=["self", "labels"])
   4801 def drop(
   4802     self,
   (...)
   4809     errors: str = "raise",
   4810 ):
   4811     """
   4812     Drop specified labels from rows or columns.
   4813 
   (...)
   4946             weight  1.0     0.8
   4947     """
-> 4948     return super().drop(
   4949         labels=labels,
   4950         axis=axis,
   4951         index=index,
   4952         columns=columns,
   4953         level=level,
   4954         inplace=inplace,
   4955         errors=errors,
   4956     )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py:4279, in NDFrame.drop(self, labels, axis, index, columns, level, inplace, errors)
   4277 for axis, labels in axes.items():
   4278     if labels is not None:
-> 4279         obj = obj._drop_axis(labels, axis, level=level, errors=errors)
   4281 if inplace:
   4282     self._update_inplace(obj)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py:4323, in NDFrame._drop_axis(self, labels, axis, level, errors, consolidate, only_slice)
   4321         new_axis = axis.drop(labels, level=level, errors=errors)
   4322     else:
-> 4323         new_axis = axis.drop(labels, errors=errors)
   4324     indexer = axis.get_indexer(new_axis)
   4326 # Case for non-unique axis
   4327 else:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py:6644, in Index.drop(self, labels, errors)
   6642 if mask.any():
   6643     if errors != "ignore":
-> 6644         raise KeyError(f"{list(labels[mask])} not found in axis")
   6645     indexer = indexer[~mask]
   6646 return self.delete(indexer)

KeyError: "[('timestamp', 'src_ip', 'dst_ip')] not found in axis

**Comment by HananHindy** [comment]
Are you sure you are looking at the right files? Could you print the column names?

**Comment by monarchinc** [comment]
yes, I have send an email to you explaining my difficulties 
Thanks

**Comment by MrGenom** [comment]
Downgrading the scikit-learn lib should fix the issue:

```
import pkg_resources
pkg_resources.require("scikit-learn==0.24.2")
```

+ adding low_memory=False on the 78th line:

`dataset = pd.read_csv(path, low_memory=False)`

**Comment by HananHindy** [comment]
Thank you for posting the fix.

**Comment by CaptainSparrow17** [comment]
> Downgrading the scikit-learn lib should fix the issue:
> 
> ```
> import pkg_resources
> pkg_resources.require("scikit-learn==0.24.2")
> ```
> 
> * adding low_memory=False on the 78th line:
> 
> `dataset = pd.read_csv(path, low_memory=False)`

I tried fixing this but getting same error. Can you please help me?
@MrGenom
